### ISSUE TITLE
Electron: Uncaught Error: No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by arstnei0** [OrJDev/solid-trpc#8] opened 2022-12-27 06:58 UTC
I am developing an app with Electron (using [electron-vite](https://github.com/alex8088/electron-vite)). It's always showing this error 
<img width="552" alt="Screenshot 2022-12-27 at 2 50 32 PM" src="https://user-images.githubusercontent.com/110709026/209624341-0151489a-c5eb-421b-96f3-989e97374492.png">

Here's the repo: https://github.com/zihan-ch/zhim
tRPC client: https://github.com/zihan-ch/zhim/blob/main/src/renderer/src/lib/trpc.ts
main.ts: https://github.com/zihan-ch/zhim/blob/main/src/renderer/src/main.tsx

When I use solid devtools to inspect the app, the context seems to be all right: 
<img width="376" alt="Screenshot 2022-12-27 at 2 57 00 PM" src="https://user-images.githubusercontent.com/110709026/209625055-48fc9c4d-4e33-465b-8776-a75b2bd8b68f.png">

I assume that this is an error inside solid-trpc; it might have done some special processes that make the context disappeared. 

ps: The app runs well without solid-trpc (the original trpc client instead).

**Comment by OrJDev** [comment] 2022-12-27 07:40
That's because the proxyclient doesn't require a trpc provider, this one does. Make sure to follow the docs and wrap your app with a trpc provider or use create jd app and it will do it for u

**Comment by OrJDev** [comment] 2022-12-27 07:56
Actually i just noticed you did, 
im not sure how electron works ive never used it, but if you try a regular app it should work ofc. I will try using it on electron.

This wouldn't work on ssr btw because solid query doesn't support ssr yet

**Comment by arstnei0** [comment] 2022-12-27 08:06
It seems that when `__useQuery` is called, the query client context isn't working. I tried to pass a `createContext(ctx.queryClient)` at the [here](https://github.com/OrJDev/solid-trpc/blob/next/src/shared/hooks/createHooksInternal.tsx#L407) and it works! This is not a nice solution but it's working. It looks like this: 
<img width="768" alt="Screenshot 2022-12-27 at 4 06 02 PM" src="https://user-images.githubusercontent.com/110709026/209633545-7faf02e3-38db-4216-a398-433584aec32f.png">

```
  function useQuery<
    TPath extends keyof TQueryValues & string,
    TQueryFnData = TQueryValues[TPath]['output'],
    TData = TQueryValues[TPath]['output'],
  >(
    pathAndInput: () => [
      path: TPath,
      ...args: inferHandlerInput<TQueries[TPath]>,
    ],
    opts?: UseTRPCQueryOptions<
      TPath,
      TQueryValues[TPath]['input'],
      TQueryFnData,
      TData,
      TError
    >,
  ): UseTRPCQueryResult<TData, TError> {
    const ctx = useContext();
    // createEffect(() => console.log("opts", opts?.()));
    if (
      typeof window === 'undefined' &&
      ctx.ssrState() === 'prepass' &&
      opts?.trpc?.ssr !== false &&
      opts?.enabled !== false &&
      !ctx.queryClient.getQueryCache().find(getArrayQueryKey(pathAndInput()))
    ) {
      void ctx.prefetchQuery(pathAndInput(), opts as any);
    }

    const shouldAbortOnUnmount = () =>
      opts?.trpc?.abortOnUnmount ?? ctx?.abortOnUnmount ?? false;
    console.log(defaultContext);
    return __useQuery(
      () => getArrayQueryKey(pathAndInput()),
      queryFunctionContext => {
        const actualOpts = () => ({
          ...opts,
          trpc: {
            ...opts?.trpc,
            ...(shouldAbortOnUnmount()
              ? {signal: queryFunctionContext.signal}
              : {}),
          },
        });
        return (ctx.client as any).query(
          ...getClientArgs(pathAndInput(), actualOpts()),
        );
      },
      {
        ...opts,
        context: createContext(ctx.queryClient),
      } as any,
    ) as UseTRPCQueryResult<TData, TError>;
  }

```

**Comment by arstnei0** [comment] 2022-12-27 08:07
Maybe it's the internal error of createQuery?

**Comment by OrJDev** [comment] 2022-12-27 12:29
no it should be working fine (if you use create jd app, which will not use electron its workin fine),
 how do i repro? i think ik what the issue is

**Comment by OrJDev** [comment] 2022-12-31 18:45
https://github.com/solidjs/vite-plugin-solid/issues/80

https://github.com/TanStack/query/issues/4673

This seems like a solid query issue, will keep you updated (according to Aryan)

Closing this for now

**Closed as not planned** 2022-12-31 18:45 UTC
